# Generated by Django 4.0.3 on 2022-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_rename_sensor_id_measurement_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo_measurement',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
