# примеры API-запросов

#@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Помидор_6",
  "description": "Лучшие помидоры на рынке_2"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/2/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=Лучшие
Content-Type: application/json

###

# поиск продуктов по id
GET {{baseUrl}}/products/?id=1
Content-Type: application/json


###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "раз три",
  "positions": [
    {
      "product": 1,
      "quantity": 11,
      "price": 11
    },
    {
      "product": 3,
      "quantity": 22,
      "price": 22
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/35/
Content-Type: application/json

{
  "positions": [
    {
      "product": 1,
      "quantity": 666,
      "price": 777
    },
    {
      "product": 3,
      "quantity": 888,
      "price": 999
    },
    {
      "product": 5,
      "quantity": 1010,
      "price": 1010
    }
  ]
}

###

# удаление склада

DELETE {{baseUrl}}/stocks/34/
Content-Type: application/json

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=1
Content-Type: application/json
